theme: jekyll-theme-slate
title: Welcome to Skip McGee's GitHub page!
production_url : https://skipmcgee.github.io
author :
  name : Skip McGee
  email : davidfranklinmcgee@gmail.com
  github : skipmcgee
JB :
  version : 0.3.0
  BASE_PATH : https://skipmcgee.github.io/reading-notes/
