theme: jekyll-theme-slate
title: Welcome to Skip McGee's GitHub page!
production_url : https://skipmcgee.github.io
author :
  name : Skip McGee
  email : davidfranklinmcgee@gmail.com
  github : skipmcgee
include: 
  - reading-notes/
  - reading-notes/README.md
  - reading-notes/initial_learning.md
JB :
  BASE_PATH : https://skipmcgee.github.io/
